[build]
  command = "pnpm install --no-frozen-lockfile && pnpm --filter ./lib/api-zod run build && pnpm --filter ./artifacts/api-server run build"
  publish = "artifacts/api-server/dist"

[functions]
  directory = "artifacts/api-server/dist"

[functions.node_bundle]

[[redirects]]
  # This forces EVERY request to go to your server function
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true