[build]
  # We added --no-frozen-lockfile here
  command = "pnpm install --no-frozen-lockfile && pnpm --filter ./lib/api-zod run build && pnpm --filter ./artifacts/api-server run build"
  publish = "artifacts/api-server/dist"

[functions]
  directory = "artifacts/api-server/dist"
  node_bundle = {}

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200